live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

[[colors.indexed_colors]]
color = "0xff966c"
index = 16

[[colors.indexed_colors]]
color = "0xc53b53"
index = 17

[colors.bright]
black = "0x444a73"
blue = "0x82aaff"
cyan = "0x86e1fc"
green = "0xc3e88d"
magenta = "0xc099ff"
red = "0xff757f"
white = "0xc8d3f5"
yellow = "0xffc777"

[colors.cursor]
cursor = "#9e4058"
text = "#ffffff"

[colors.normal]
black = "0x1b1d2b"
blue = "0x82aaff"
cyan = "0x86e1fc"
green = "0xc3e88d"
magenta = "0xc099ff"
red = "0xff757f"
white = "0x828bb8"
yellow = "0xffc777"

[colors.primary]
background = "0x222436"
foreground = "0xc8d3f5"

[colors.search.matches]
background = "#ffffff"
foreground = "#FF1493"

[font.bold]
family = "Lekton Nerd Font"
style = "Bold"

[font.italic]
family = "iosevka"
style = "Italic Bold"

[font.normal]
family = "Monego Nerd Font Fix"
style = "Regular"

[font.offset]
x = 0
y = 2

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[scrolling]
history = 0

[window]
decorations = "none"
opacity = 0.8
